Repository NotifyTeam/i18n, pull requests merged in 2019-12, with the labels that each got.

#2 Norwegian translation
  index.ts
  json/no.json
Labels: enhancement, translation

#6 Added Spanish translation
  json/es.json
Labels: translation

#7 Added Pirate Speak
  .github/pull_request_template.md
  json/pirate.json
Labels: translation

#8 Flubbed the pr template
  .github/pull_request_template.md
Labels: fix

#9 Added Swedish
  index.js
  json/sv.json
Labels: translation

#12 Italian language update
  json/it.json
Labels: enhancement
